# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RomanWalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RomanWalk
  pod 'Firebase/Firestore'
  pod 'SwiftMessages'
  pod 'PureLayout'
  pod 'Kingfisher'
  pod 'SwiftEventBus'
  pod 'ReachabilitySwift'

end

target 'RomanWalkQuizTests' do
   inherit! :search_paths
end
